// SPDX-License-Identifier: Apache-2.0 OR MIT

#![cfg(nightly)]
#![no_core]
#![feature(no_core)]

// Make sure the items generated by pin-project-lite don't depend on paths like
// `core`, `core::prelude::*`, etc.
//
// Note:
// - pin-project-lite depends on core's items and is not really usable
//   in a no-core environment.

extern crate core as _core;

// Dummy module to check that the expansion refers to the crate.
mod pin_project_lite {}

pub mod module {
    use _core::{fmt::Debug, include, prelude::v1::derive};

    include!("../include/basic.rs");
}

use _core::{fmt::Debug, include, prelude::v1::derive};

include!("../include/basic.rs");
